### ISSUE TITLE
Detailed instructions

### ISSUE THREAD

**Issue by JasonPolisAdmin** [kinow/protobuf-uml-diagram#40]
Hi, 
It would benefit from detailed instructions on how to get running,
including sample input .proto and output .png
to check whether installation succesful.

**Comment by ManishMaheshwari** [comment]
+1

**Comment by kinow** [comment]
Hi! Was going to write a more detailed Getting Started section or Wiki page, but I don't have much time right now. Instead of leaving it open for longer, wrote a short TL;DR section so others can follow the steps and confirm the installation is working, and also learn by copying an example.

https://github.com/kinow/protobuf-uml-diagram#tldr

Thanks!

**Comment by JasonPolisAdmin** [comment]
Thanks. Got that base test working now.
Please also add that it depends on the installation of [graphviz](https://www.graphviz.org/download/), or else it reports
`graphviz.backend.execute.ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH`.

**Comment by kinow** [comment]
> Thanks. Got that base test working now. Please also add that it depends on the installation of [graphviz](https://www.graphviz.org/download/), or else it reports `graphviz.backend.execute.ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH`.

Ah good idea. Would you like to send a PR for that?
